// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbBaseMessage.proto

package com.amuer.aurora.base.protocol.protobuf;

public final class PbBaseMessage {
  private String string;

  private PbBaseMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }

  public interface BaseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.amuer.aurora.base.protocol.protobuf.BaseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 serverType = 1;</code>
     */
    boolean hasServerType();
    /**
     * <code>required int32 serverType = 1;</code>
     */
    int getServerType();

    /**
     * <code>required int32 serverID = 2;</code>
     */
    boolean hasServerID();
    /**
     * <code>required int32 serverID = 2;</code>
     */
    int getServerID();
  }
  /**
   * Protobuf type {@code com.amuer.aurora.base.protocol.protobuf.BaseMessage}
   */
  public static final class BaseMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.amuer.aurora.base.protocol.protobuf.BaseMessage)
      BaseMessageOrBuilder {
    // Use BaseMessage.newBuilder() to construct.
    private BaseMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BaseMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BaseMessage defaultInstance;
    public static BaseMessage getDefaultInstance() {
      return defaultInstance;
    }

    public BaseMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BaseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              serverType_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              serverID_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.internal_static_com_amuer_aurora_base_protocol_protobuf_BaseMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.internal_static_com_amuer_aurora_base_protocol_protobuf_BaseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessage.class, com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<BaseMessage> PARSER =
        new com.google.protobuf.AbstractParser<BaseMessage>() {
      public BaseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BaseMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SERVERTYPE_FIELD_NUMBER = 1;
    private int serverType_;
    /**
     * <code>required int32 serverType = 1;</code>
     */
    public boolean hasServerType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 serverType = 1;</code>
     */
    public int getServerType() {
      return serverType_;
    }

    public static final int SERVERID_FIELD_NUMBER = 2;
    private int serverID_;
    /**
     * <code>required int32 serverID = 2;</code>
     */
    public boolean hasServerID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 serverID = 2;</code>
     */
    public int getServerID() {
      return serverID_;
    }

    private void initFields() {
      serverType_ = 0;
      serverID_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasServerType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServerID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, serverType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, serverID_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, serverType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, serverID_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.amuer.aurora.base.protocol.protobuf.BaseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.amuer.aurora.base.protocol.protobuf.BaseMessage)
        com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.internal_static_com_amuer_aurora_base_protocol_protobuf_BaseMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.internal_static_com_amuer_aurora_base_protocol_protobuf_BaseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessage.class, com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessage.Builder.class);
      }

      // Construct using com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serverType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        serverID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.internal_static_com_amuer_aurora_base_protocol_protobuf_BaseMessage_descriptor;
      }

      public com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessage getDefaultInstanceForType() {
        return com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessage.getDefaultInstance();
      }

      public com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessage build() {
        com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessage buildPartial() {
        com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessage result = new com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverType_ = serverType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.serverID_ = serverID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessage) {
          return mergeFrom((com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessage other) {
        if (other == com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessage.getDefaultInstance()) return this;
        if (other.hasServerType()) {
          setServerType(other.getServerType());
        }
        if (other.hasServerID()) {
          setServerID(other.getServerID());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServerType()) {
          
          return false;
        }
        if (!hasServerID()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.amuer.aurora.base.protocol.protobuf.PbBaseMessage.BaseMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int serverType_ ;
      /**
       * <code>required int32 serverType = 1;</code>
       */
      public boolean hasServerType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 serverType = 1;</code>
       */
      public int getServerType() {
        return serverType_;
      }
      /**
       * <code>required int32 serverType = 1;</code>
       */
      public Builder setServerType(int value) {
        bitField0_ |= 0x00000001;
        serverType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 serverType = 1;</code>
       */
      public Builder clearServerType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverType_ = 0;
        onChanged();
        return this;
      }

      private int serverID_ ;
      /**
       * <code>required int32 serverID = 2;</code>
       */
      public boolean hasServerID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 serverID = 2;</code>
       */
      public int getServerID() {
        return serverID_;
      }
      /**
       * <code>required int32 serverID = 2;</code>
       */
      public Builder setServerID(int value) {
        bitField0_ |= 0x00000002;
        serverID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 serverID = 2;</code>
       */
      public Builder clearServerID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        serverID_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.amuer.aurora.base.protocol.protobuf.BaseMessage)
    }

    static {
      defaultInstance = new BaseMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.amuer.aurora.base.protocol.protobuf.BaseMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_amuer_aurora_base_protocol_protobuf_BaseMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_amuer_aurora_base_protocol_protobuf_BaseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023pbBaseMessage.proto\022\'com.amuer.aurora." +
      "base.protocol.protobuf\"3\n\013BaseMessage\022\022\n" +
      "\nserverType\030\001 \002(\005\022\020\n\010serverID\030\002 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_amuer_aurora_base_protocol_protobuf_BaseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_amuer_aurora_base_protocol_protobuf_BaseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_amuer_aurora_base_protocol_protobuf_BaseMessage_descriptor,
        new java.lang.String[] { "ServerType", "ServerID", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
